// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxB53QY3l_Of6CyN1z0h46gWpFh72j5Qg',
    appId: '1:191729698183:web:99830b64950ea8c0bbff22',
    messagingSenderId: '191729698183',
    projectId: 'belajar-firebase-e84ae',
    authDomain: 'belajar-firebase-e84ae.firebaseapp.com',
    storageBucket: 'belajar-firebase-e84ae.appspot.com',
    measurementId: 'G-HYWEN6X71B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbkqj494-J8wnT-_I5y-rBAk0gzwQ28Ic',
    appId: '1:191729698183:android:3257a444ac056bdfbbff22',
    messagingSenderId: '191729698183',
    projectId: 'belajar-firebase-e84ae',
    storageBucket: 'belajar-firebase-e84ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNzBwzpoy9Y6ZOCH7ZDTtVkldqVUFr8Us',
    appId: '1:191729698183:ios:b0881eb799dfb239bbff22',
    messagingSenderId: '191729698183',
    projectId: 'belajar-firebase-e84ae',
    storageBucket: 'belajar-firebase-e84ae.appspot.com',
    iosBundleId: 'com.example.belajarFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNzBwzpoy9Y6ZOCH7ZDTtVkldqVUFr8Us',
    appId: '1:191729698183:ios:08ffdd6807f7ee34bbff22',
    messagingSenderId: '191729698183',
    projectId: 'belajar-firebase-e84ae',
    storageBucket: 'belajar-firebase-e84ae.appspot.com',
    iosBundleId: 'com.example.belajarFirebase.RunnerTests',
  );
}
